config/routes.rb
Smurfy::Application.routes.draw do
  resources :tables

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/table.rb
class Table < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, :notice => 'Table was successfully created.' }
        format.json { render :json => @table, :status => :created, :location => @table }
      else
        format.html { render :action => "new" }
        format.json { render :json => @table.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, :notice => 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @table.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smurfy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "bootstrap", :media => "all" %>
    <%= stylesheet_link_tag "bootstrap-responsive", :media => "all" %>
    <%= stylesheet_link_tag "main", :media => "all" %>

</head>
<body>

<p>H</p>

<%= yield %>

</body>
</html>

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tables.each do |table| %>
  <tr>
    <td><%= table.name %></td>
    <td><%= table.number %></td>
    <td><%= link_to 'Show', table %></td>
    <td><%= link_to 'Edit', edit_table_path(table) %></td>
    <td><%= link_to 'Destroy', table, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @table.name %>
</p>

<p>
  <b>Number:</b>
  <%= @table.number %>
</p>


<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>